/******  CREAZIONE DB ******/
USE [master]
GO
CREATE DATABASE [QUIZ]

/****** CREA Table [dbo].[ASSICURAZIONI] ******/
USE [QUIZ]
GO
CREATE TABLE [dbo].[ASSICURAZIONI](
	[CodAss] [nvarchar](20) NOT NULL,
	[Nome] [nchar](20) NULL,
	[Sede] [nvarchar](50) NULL,
 CONSTRAINT [PK_ASSICURAZIONI] PRIMARY KEY CLUSTERED 
(
	[CodAss] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** CREA Table [dbo].[AUTO] ******/
USE [QUIZ]
GO
CREATE TABLE [dbo].[AUTO](
	[Targa] [nvarchar](10) NOT NULL,
	[Marca] [nchar](20) NULL,
	[Cilindrata] [int] NULL,
	[Potenza] [int] NULL,
	[CodF] [nvarchar](16) NOT NULL,
	[CodAss] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_AUTO] PRIMARY KEY CLUSTERED 
(
	[Targa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** CREA Table [dbo].[PROPRIETARI] ******/
USE [QUIZ]
GO
CREATE TABLE [dbo].[PROPRIETARI](
	[CodF] [nvarchar](16) NOT NULL,
	[Nome] [nchar](20) NULL,
	[Residenza] [nvarchar](50) NULL,
 CONSTRAINT [PK_PROPRIETARI] PRIMARY KEY CLUSTERED 
(
	[CodF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** CREA Table [dbo].[SINISTRI] ******/
CREATE TABLE [dbo].[SINISTRI](
	[CodS] [nvarchar](20) NOT NULL,
	[Località] [nvarchar](50) NULL,
	[Data] [numeric](10, 0) NOT NULL,
 CONSTRAINT [PK_CodS] PRIMARY KEY CLUSTERED 
(
	[CodS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** CREA Table [dbo].[AUTOCOINVOLTE] ******/
CREATE TABLE [dbo].[AUTOCOINVOLTE](
	[CodS] [nvarchar](20) NOT NULL,
	[Targa] [nvarchar](10) NOT NULL,
	[ImportoDelDanno] [numeric](18, 2) NULL,
 CONSTRAINT [PK_AUTOCOINVOLTE] PRIMARY KEY CLUSTERED 
(
	[CodS] ASC,
	[Targa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUTOCOINVOLTE]  WITH CHECK ADD  CONSTRAINT [FK_CodS] FOREIGN KEY([CodS])
REFERENCES [dbo].[SINISTRI] ([CodS])
ALTER TABLE [dbo].[AUTOCOINVOLTE] CHECK CONSTRAINT [FK_CodS]
ALTER TABLE [dbo].[AUTOCOINVOLTE]  WITH CHECK ADD  CONSTRAINT [FK_Targa] FOREIGN KEY([Targa])
REFERENCES [dbo].[AUTO] ([Targa])
ALTER TABLE [dbo].[AUTOCOINVOLTE] CHECK CONSTRAINT [FK_Targa]
GO

/****** CREA Table [dbo].[TestCSVImport]  ******/
CREATE TABLE [dbo].[TestCSVImport](
	[CodS] [nvarchar](20) NULL,
	[Località] [nvarchar](50) NULL,
	[Data] [nvarchar](50) NULL
) ON [PRIMARY]
GO
